### ISSUE TITLE
Cross-thread operation not valid: Control 'quickSearchBox' accessedfrom a thread other than the thread it was created on

### ISSUE THREAD

**Issue by baerrach** [GeertBellekens/Enterprise-Architect-Toolpack#124]
```
16-08-2023 06:00:13.519 diff: 117918.1342 ms Error: An unhandled exception has occured.
Error Message: Cross-thread operation not valid: Control 'quickSearchBox' accessed from a thread other than the thread it was created on.
Stacktrace:    at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.ToolTip.Hide(IWin32Window win)
   at TSF.UmlToolingFramework.EANavigator.QuickSearchBox.set_DroppedDown(Boolean value) in C:\Users\treloarb\code\Enterprise-Architect-Toolpack\EANavigator\QuickSearchBox.cs:line 50
   at TSF.UmlToolingFramework.EANavigator.NavigatorControl.treeBackgroundRunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\Users\treloarb\code\Enterprise-Architect-Toolpack\EANavigator\NavigatorControl.cs:line 158
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by baerrach** [comment]
Had a new model,
clicking around in menu
Design
> Model/Diagram/Element
> Manage

when this stack trace popped up.
