### ISSUE TITLE
EA => TFS Not working for TFS 2017

### ISSUE THREAD

**Issue by Chrissteven81** [GeertBellekens/Enterprise-Architect-Toolpack#70]
Field/EXT_REFID is a missing field

**Comment by gbarrett7124** [comment]
Is this the message you get? 

![image](https://user-images.githubusercontent.com/9001078/34906332-545ff25c-f820-11e7-99eb-3873251fb759.png)

I'm seeing this connecting to a XXX.visualstudio.com address.

**Comment by pjezek** [comment]
Method **updateEAGUIDToTFS** fails to update **EA's GUID** into field **Ext_RefId**. 
Solution: Add a field with this name to your Work Items in TFS. Then import should work again.
@gbarrett7124: yes

**Comment by jpfarhadian** [comment]
I always get this error connect VSTO https://xxx.visualstudio.com trying to get requirement from TFS -> EA. I can browse to the site so project settings are OK. 
What is the mediatypeformatter used (JSON, XML, text) ?

Error Message: No MediaTypeFormatter is available to read an object of type 'WorkItemQueryResult' from content with media type 'text/html'.
Stacktrace:    at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, IEnumerable`1 formatters)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content)
   at EAAddinFramework.WorkTracking.TFS.TFSProject.getAllWorkitems() in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Add-in-Framework\EAAddinFramework\WorkTracking\TFS\TFSProject.cs:line 175
   at EAAddinFramework.WorkTracking.TFS.TFSProject.get_workitems() in C:\Users\LaptopGeert\Documents\GitHub\Enterprise-Architect-Add-in-Framework\EAAddinFramework\WorkTracking\TFS\TFSProject.cs:line 83
   at EATFSConnector.EATFSConnectorAddin.synchTFSToEA()
